### ISSUE TITLE
[Bug]: haproxy: can't chose between an ECDSA or RSA certificate

### ISSUE THREAD

**Issue by wlallemand** [wolfSSL/wolfssl#6893]
### Version

210fff556951

### Description

With OpenSSL, HAProxy uses the client hello callback `SSL_CTX_set_client_hello_cb()`  and `SSL_client_hello_get0_ext()` to chose precisely which certificate we want to use, using specific filters, SNI or the type of key.

Each certificates are stored in a tree and each are in a SSL_CTX. This way we have an SSL_CTX for each SNI and key.
HAProxy gives the users the ability to write filters so they can specifiy a specific file for an SNI.

For example:
```
file               |        SNI filters
bar.com.pem.ecdsa      bar.com *.bar.com
bar.com.pem.rsa        bar.com *.bar.com
foo.bar.com.pem.rsa    foo.bar.com
```

Basically each line will generate an SSL_CTX, which will be chosen during the client hello.

With WolfSSL, the client hello callback is not available, only `SSL_CTX_set_tlsext_servername_callback()` or the `SSL_CTX_set_cert_cb()` callback can be used. It's enough to chose a certificate based on the SNI, but we don't have  `SSL_client_hello_get0_ext(ssl, TLSEXT_TYPE_signature_algorithms`, here, nor the ciphers with `SSL_client_hello_get0_ciphers()`.

I tried to implement an alternative with `SSL_CTX_set_cert_cb()` but `SSL_get_client_ciphers()` does not seem to exists in WolfSSL to get the client ciphers, and I can't find a way to get the TLSEXT_TYPE_signature_algorithms ?

Unfortunately we are not able of serving both RSA and ECDSA for the same domain without this.

Do you have any suggestions or solutions for this problem?

Regards,

**Comment by embhorn** [comment]
Hello @wlallemand 

Thanks for submitting this report. I'll review with the team and report back.

Kind regards,
@embhorn - wolfSSL Support

**Comment by julek-wolfssl** [comment]
Hi @wlallemand,

are you trying to choose the ciphersuite/sigalg based on the client's parameters or just the certificate? Unfortunately, I don't see a way for the user to see the ciphers provided by the peer. This will require some work to expose these values to the user.

Sincerely
Juliusz

**Comment by wlallemand** [comment]
Hello @julek-wolfssl,

I'm trying to chose a specific SSL_CTX based on the client hello, so I need something like `SSL_client_hello_get0_ciphers()`  and `SSL_client_hello_get0_ext(ssl, TLSEXT_TYPE_signature_algorithms`.

If that is not possible, what is the recommended way with wolfSSL to have a dual certificate ECDSA/RSA for the same domain?

Regards,

**Comment by julek-wolfssl** [comment]
Hi @wlallemand,

from what I can tell, there is no way to access the client's advertised ciphersuite list and their sigalgs. I will add some API's for this and keep you up to date.

Sincerely
Juliusz

**Comment by wlallemand** [comment]
Thanks for the feedback, if you want to see more details about how we do this the client hello callback that we are using is here: https://github.com/haproxy/haproxy/blob/master/src/ssl_sock.c#L2339

**Comment by julek-wolfssl** [comment]
@wlallemand 
I added APIs to allow choosing certs based on the cipher list and the sigalgs in https://github.com/wolfSSL/wolfssl/pull/6963. In the PR, you can look at the `test_wolfSSL_cert_cb_dyn_ciphers` test to see how to use this API. The user callback is `test_wolfSSL_cert_cb_dyn_ciphers_certCB` where I use a new API `wolfSSL_get_client_suites_sigalgs` to get access to the raw list of ciphers and sigalgs. The sigalg parsing is not very pretty because we don't expose these values but in the future maybe we can add some `sigalg -> string description` API to make it easier on the user.

The PR will be failing many tests for now because I haven't gated the new additions properly and only tested it with `--enable-haproxy` and `--enable-opensslall`. It is ready for you to test it out.

**Comment by julek-wolfssl** [comment]
Also keep in mind that `wolfSSL_get_client_suites_sigalgs` returns the direct list of ciphers and sigalgs provided by the user. It is not filtered on common values.

**Comment by wlallemand** [comment]
Thanks a lot!  I'll try it out soon and give you feedbacks about it!

**Comment by julek-wolfssl** [comment]
@wlallemand I added another API `wolfSSL_get_ciphersuite_info` to make ciphersuite parsing cleaner and faster. This no longer relies on string parsing. It uses our builtin checks for what each ciphersuite needs so it should be complete with all the ciphers we support or are built with. Let me know if this is a better solution for you.

**Comment by wlallemand** [comment]
Thanks for this new API, I updated my code, this is really better. Do you think something like this could also be done for the SigAlgs? Because the switch/case is kind of dark magic if you don't know the wolfssl internals! :)

 I could make it work correctly with TLSv1.2. However I can't test it correctly with TLSv1.3 and I feel like I'm missing something, using SSL_CTX_set1_sigalgs_list() with the sigalgs algorithms from TLSv1.3 does not seem to work, I tried mutiple ones from the RFC (https://datatracker.ietf.org/doc/html/rfc8446#section-4.2.3) . OpenSSL use the names from the enums, am I suppose to use something else with WolfSSL?

**Comment by julek-wolfssl** [comment]
I'll look into a sigalgs equivalent.

Regarding using `SSL_CTX_set1_sigalgs_list`, take a look at `test_wolfSSL_cert_cb_dyn_ciphers`. There I use the same API to set the sigalgs. Can you try using one of the sigalgs used in the test?

**Comment by julek-wolfssl** [comment]
I pushed one more new API `wolfSSL_get_sigalg_info`. Please take a looks at the same tests to see how to use it.

**Comment by wlallemand** [comment]
> I'll look into a sigalgs equivalent. 

Thanks!

> Regarding using `SSL_CTX_set1_sigalgs_list`, take a look at `test_wolfSSL_cert_cb_dyn_ciphers`. There I use the same API to set the sigalgs. Can you try using one of the sigalgs used in the test?

It looks like it worked correctly with the format used in TLS1.2 indeed! I converted my tests as it seems to work with OpenSSL as well. I wonder if the users need the TLS1.3 format, thought.

> I pushed one more new API wolfSSL_get_sigalg_info. Please take a looks at the same tests to see how to use it.

Great, I'm testing it.

**Comment by julek-wolfssl** [comment]
> I wonder if the users need the TLS1.3 format

Can you give an example of the formats? I'll check if/how we can support it.

**Comment by wlallemand** [comment]
It uses the same format with ":" as a separator, but the sigalg name is a SignatureScheme from the TLSv1.3 RFC.
For example `rsa_pss_rsae_sha384:rsa_pkcs1_sha256:ecdsa_secp384r1_sha384`, `rsa_pss_rsae_sha384:rsa_pkcs1_sha256` etc

I updated my code with the wolfSSL_get_sigalg_info() API. So far the simple regression tests seems to be working, I have failures on some cases but I  think that's a problem in HAProxy, I didn't find out the cause yet.

**Comment by julek-wolfssl** [comment]
I'll make a note to look into supporting the new signature names.

**Comment by julek-wolfssl** [comment]
As a heads up. I had to change up some of the types in the functions to accommodate for some annoying backwards compatibility. The functionality is still the same, but we're going to rely a bit more on documentation to know what the types being returned are.
