### ISSUE TITLE
More outside array bounds warnings from GCC: wolfcrypt/src/sp_int.c

### ISSUE THREAD

**Issue by tjko** [wolfSSL/wolfssl#8999]
### Version

5.8.0 

### Description

(This is related to #8951)

When compiling for RP2350 getting these errors (but not getting these when targeting RP2040)

```
In function 'sp_clear',
    inlined from 'sp_clear' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:5262:6,
    inlined from '_sp_prime_trials' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19298:9,
    inlined from 'sp_prime_is_prime' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19368:15:
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:5272:26: warning: array subscript 'sp_int[0]' is partly outside array bounds of 'sp_int[0]' [-Warray-bounds=]
 5272 |         for (i = 0; i < a->used; i++) {
      |                         ~^~~~~~
In file included from /home/tjko/git/fanpico/libs/wolfssl/wolfssl/wolfcrypt/libwolfssl_sources.h:46,
                 from /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:30:
In function '_sp_prime_trials',
    inlined from 'sp_prime_is_prime' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19368:15:
/home/tjko/git/fanpico/libs/wolfssl/wolfssl/wolfcrypt/types.h:571:61: note: object of size [8, 40] allocated by 'malloc'
  571 |         #define XMALLOC(s, h, t)     ((void)(h), (void)(t), malloc((size_t)(s))) /* native heap */
      |                                                             ^~~~~~~~~~~~~~~~~~~
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:148:28: note: in expansion of macro 'XMALLOC'
  148 |             (n) = (sp_int*)XMALLOC(MP_INT_SIZEOF(s), (h),                      \
      |                            ^~~~~~~
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19278:5: note: in expansion of macro 'ALLOC_SP_INT'
19278 |     ALLOC_SP_INT(n1, a->used + 1, err, NULL);
      |     ^~~~~~~~~~~~
In function 'sp_clear',
    inlined from 'sp_clear' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:5262:6,
    inlined from '_sp_prime_trials' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19299:9,
    inlined from 'sp_prime_is_prime' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19368:15:
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:5272:26: warning: array subscript 'sp_int[0]' is partly outside array bounds of 'unsigned char[40]' [-Warray-bounds=]
 5272 |         for (i = 0; i < a->used; i++) {
      |                         ~^~~~~~
In function '_sp_prime_trials',
    inlined from 'sp_prime_is_prime' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19368:15:
/home/tjko/git/fanpico/libs/wolfssl/wolfssl/wolfcrypt/types.h:571:61: note: object of size [8, 40] allocated by 'malloc'
  571 |         #define XMALLOC(s, h, t)     ((void)(h), (void)(t), malloc((size_t)(s))) /* native heap */
      |                                                             ^~~~~~~~~~~~~~~~~~~
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:148:28: note: in expansion of macro 'XMALLOC'
  148 |             (n) = (sp_int*)XMALLOC(MP_INT_SIZEOF(s), (h),                      \
      |                            ^~~~~~~
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19279:5: note: in expansion of macro 'ALLOC_SP_INT'
19279 |     ALLOC_SP_INT(r, a->used + 1, err, NULL);
      |     ^~~~~~~~~~~~
In function 'sp_clear',
    inlined from 'sp_clear' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:5262:6,
    inlined from '_sp_prime_trials' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19299:9,
    inlined from 'sp_prime_is_prime' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19368:15:
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:5273:22: warning: array subscript 'sp_int[0]' is partly outside array bounds of 'unsigned char[40]' [-Warray-bounds=]
 5273 |             a->dp[i] = 0;
      |             ~~~~~~~~~^~~
In function '_sp_prime_trials',
    inlined from 'sp_prime_is_prime' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19368:15:
[ 82%] Building C object CMakeFiles/fanpico.dir/home/tjko/pico/pico-sdk/lib/mbedtls/library/aes.c.o
/home/tjko/git/fanpico/libs/wolfssl/wolfssl/wolfcrypt/types.h:571:61: note: object of size [8, 40] allocated by 'malloc'
  571 |         #define XMALLOC(s, h, t)     ((void)(h), (void)(t), malloc((size_t)(s))) /* native heap */
      |                                                             ^~~~~~~~~~~~~~~~~~~
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:148:28: note: in expansion of macro 'XMALLOC'
  148 |             (n) = (sp_int*)XMALLOC(MP_INT_SIZEOF(s), (h),                      \
      |                            ^~~~~~~
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19279:5: note: in expansion of macro 'ALLOC_SP_INT'
19279 |     ALLOC_SP_INT(r, a->used + 1, err, NULL);
      |     ^~~~~~~~~~~~
In function 'sp_clear',
    inlined from 'sp_clear' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:5262:6,
    inlined from '_sp_prime_trials' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19298:9,
    inlined from 'sp_prime_is_prime' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19368:15:
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:5273:22: warning: array subscript 'sp_int[0]' is partly outside array bounds of 'sp_int[0]' [-Warray-bounds=]
 5273 |             a->dp[i] = 0;
      |             ~~~~~~~~~^~~
In function '_sp_prime_trials',
    inlined from 'sp_prime_is_prime' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19368:15:
/home/tjko/git/fanpico/libs/wolfssl/wolfssl/wolfcrypt/types.h:571:61: note: object of size [8, 40] allocated by 'malloc'
  571 |         #define XMALLOC(s, h, t)     ((void)(h), (void)(t), malloc((size_t)(s))) /* native heap */
      |                                                             ^~~~~~~~~~~~~~~~~~~
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:148:28: note: in expansion of macro 'XMALLOC'
  148 |             (n) = (sp_int*)XMALLOC(MP_INT_SIZEOF(s), (h),                      \
      |                            ^~~~~~~
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19278:5: note: in expansion of macro 'ALLOC_SP_INT'
19278 |     ALLOC_SP_INT(n1, a->used + 1, err, NULL);
      |     ^~~~~~~~~~~~
```

To reproduce these see (#8951 notes), only difference here is to target Pico 2 (RP2350) vs Pico (RP2040);

```
mkdir build
cd build
cmake -DPICO_BOARD=pico2_w ..
make -j
```

**Comment by tjko** [comment]
Github actions build log showing these can be found here: 
https://github.com/tjko/fanpico/actions/runs/16212225117/job/45774386628#logs

(in the "Build" step)

**Comment by SparkiDev** [comment]
Hi @tjko,

Looking at the warning, I can see that it isn't valid.
The compiler is saying:
```
... array subscript 'sp_int[0]' is partly outside array bounds of 'sp_int[0]'
```

This indicates to me it doesn't know how big an sp_int is or is confusing it with an sp_int_minial.

If you turn off inlining of _sp_prime_trials(), does this make the compilation error go away?

Can you please let us know the compile line for sp_int.c?
I can't reproduce the issue locally with the information I have.

Thanks,
Sean

**Comment by tjko** [comment]
Here's the command CMake ended up invoking:
```
/opt/arm-gnu-toolchain/bin/arm-none-eabi-gcc -DCFG_TUSB_DEBUG=0 -DCFG_TUSB_MCU=OPT_MCU_RP2040 -DCFG_TUSB_OS=OPT_OS_PICO -DCYW43_LWIP=1 -DLFS_NO_DEBUG=1 -DLFS_THREADSAFE=1 -DLIB_BOOT_STAGE2_HEADERS=1 -DLIB_PICO_AON_TIMER=1 -DLIB_PICO_ASYNC_CONTEXT_THREADSAFE_BACKGROUND=1 -DLIB_PICO_ATOMIC=1 -DLIB_PICO_BIT_OPS=1 -DLIB_PICO_BIT_OPS_PICO=1 -DLIB_PICO_CLIB_INTERFACE=1 -DLIB_PICO_CRT0=1 -DLIB_PICO_CXX_OPTIONS=1 -DLIB_PICO_CYW43_ARCH=1 -DLIB_PICO_DIVIDER=1 -DLIB_PICO_DIVIDER_COMPILER=1 -DLIB_PICO_DOUBLE=1 -DLIB_PICO_DOUBLE_PICO=1 -DLIB_PICO_FIX_RP2040_USB_DEVICE_ENUMERATION=1 -DLIB_PICO_FLASH=1 -DLIB_PICO_FLOAT=1 -DLIB_PICO_FLOAT_PICO=1 -DLIB_PICO_FLOAT_PICO_VFP=1 -DLIB_PICO_INT64_OPS=1 -DLIB_PICO_INT64_OPS_COMPILER=1 -DLIB_PICO_MALLOC=1 -DLIB_PICO_MEM_OPS=1 -DLIB_PICO_MEM_OPS_COMPILER=1 -DLIB_PICO_MULTICORE=1 -DLIB_PICO_NEWLIB_INTERFACE=1 -DLIB_PICO_PLATFORM=1 -DLIB_PICO_PLATFORM_COMPILER=1 -DLIB_PICO_PLATFORM_PANIC=1 -DLIB_PICO_PLATFORM_SECTIONS=1 -DLIB_PICO_PRINTF=1 -DLIB_PICO_PRINTF_PICO=1 -DLIB_PICO_RAND=1 -DLIB_PICO_RUNTIME=1 -DLIB_PICO_RUNTIME_INIT=1 -DLIB_PICO_SHA256=1 -DLIB_PICO_STANDARD_BINARY_INFO=1 -DLIB_PICO_STANDARD_LINK=1 -DLIB_PICO_STDIO=1 -DLIB_PICO_STDIO_UART=1 -DLIB_PICO_STDIO_USB=1 -DLIB_PICO_STDLIB=1 -DLIB_PICO_SYNC=1 -DLIB_PICO_SYNC_CRITICAL_SECTION=1 -DLIB_PICO_SYNC_MUTEX=1 -DLIB_PICO_SYNC_SEM=1 -DLIB_PICO_TIME=1 -DLIB_PICO_TIME_ADAPTER=1 -DLIB_PICO_UNIQUE_ID=1 -DLIB_PICO_UTIL=1 -DMBEDTLS_CONFIG_FILE=\"mbedtls_config.h\" -DPARAM_ASSERTIONS_ENABLE_ALL=1 -DPICO_32BIT=1 -DPICO_BOARD=\"pico2_w\" -DPICO_BUILD=1 -DPICO_CMAKE_BUILD_TYPE=\"Release\" -DPICO_COPY_TO_RAM=0 -DPICO_CORE1_STACK_SIZE=0x1000 -DPICO_CXX_ENABLE_EXCEPTIONS=0 -DPICO_CYW43_ARCH_THREADSAFE_BACKGROUND=1 -DPICO_DEBUG_MALLOC=0 -DPICO_MALLOC_PANIC=0 -DPICO_NO_FLASH=0 -DPICO_NO_HARDWARE=0 -DPICO_ON_DEVICE=1 -DPICO_RP2040_USB_DEVICE_ENUMERATION_FIX=1 -DPICO_RP2040_USB_DEVICE_UFRAME_FIX=1 -DPICO_RP2350=1 -DPICO_STACK_SIZE=0x2000 -DPICO_TARGET_NAME=\"fanpico\" -DPICO_USE_BLOCKED_RAM=0 -DPICO_USE_FASTEST_SUPPORTED_CLOCK=1 -DPICO_USE_STACK_GUARDS=1 -DUSBD_DESC_STR_MAX=32 -DUSBD_MANUFACTURER="\"TJKO Industries\"" -DUSBD_PRODUCT="\"FanPico-0804D Fan Controller\"" -DWOLFSSH_USER_IO -DWOLFSSL_SP_ARM_CORTEX_M_ASM -DWOLFSSL_USER_SETTINGS -Dwolfssl -I/home/tjko/git/fanpico/src/wolfssl -I/home/tjko/git/fanpico/build2 -I/home/tjko/git/fanpico/src -I/home/tjko/pico/pico-sdk/src/rp2_common/pico_atomic/include -I/home/tjko/pico/pico-sdk/lib/tinyusb/src -I/home/tjko/git/fanpico/libs/pico-lfs/src -I/home/tjko/git/fanpico/libs/pico-lfs/libs/littlefs -I/home/tjko/git/fanpico/libs/cJSON -I/home/tjko/git/fanpico/libs/ss_oled-lib -I/home/tjko/git/fanpico/libs/bb_spi_lcd-lib -I/home/tjko/git/fanpico/libs/libb64/include -I/home/tjko/git/fanpico/libs/pico-1wire-lib/include -I/home/tjko/git/fanpico/libs/pico-sensor-lib/include -I/home/tjko/git/fanpico/build2/pico-sdk/src/rp2_common/pico_cyw43_driver -I/home/tjko/git/fanpico/libs/pico-telnetd/include -I/home/tjko/git/fanpico/libs/pico-sshd/include -I/home/tjko/git/fanpico/libs/wolfssl -I/home/tjko/git/fanpico/libs/wolfssh -isystem /home/tjko/pico/pico-sdk/src/common/pico_stdlib_headers/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_gpio/include -isystem /home/tjko/pico/pico-sdk/src/common/pico_base_headers/include -isystem /home/tjko/git/fanpico/build2/generated/pico_base -isystem /home/tjko/pico/pico-sdk/src/boards/include -isystem /home/tjko/pico/pico-sdk/src/rp2350/pico_platform/include -isystem /home/tjko/pico/pico-sdk/src/rp2350/hardware_regs/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_base/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_platform_compiler/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_platform_panic/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_platform_sections/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_dcp/include -isystem /home/tjko/pico/pico-sdk/src/rp2350/hardware_structs/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_rcp/include -isystem /home/tjko/pico/pico-sdk/src/common/hardware_claim/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_sync/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_sync_spin_lock/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_irq/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_uart/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_resets/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_clocks/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_pll/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_vreg/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_watchdog/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_ticks/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_bootrom/include -isystem /home/tjko/pico/pico-sdk/src/common/boot_picoboot_headers/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/boot_bootrom_headers/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_boot_lock/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_flash/include -isystem /home/tjko/pico/pico-sdk/src/common/pico_time/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_timer/include -isystem /home/tjko/pico/pico-sdk/src/common/pico_sync/include -isystem /home/tjko/pico/pico-sdk/src/common/pico_util/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_time_adapter/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_xosc/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_divider/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_runtime/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_runtime_init/include -isystem /home/tjko/pico/pico-sdk/src/common/pico_bit_ops_headers/include -isystem /home/tjko/pico/pico-sdk/src/common/pico_divider_headers/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_double/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_float/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_malloc/include -isystem /home/tjko/pico/pico-sdk/src/common/pico_binary_info/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_printf/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_stdio/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_stdio_usb/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_unique_id/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_flash/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_xip_cache/include -isystem /home/tjko/pico/pico-sdk/src/common/pico_usb_reset_interface_headers/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_multicore/include -isystem /home/tjko/pico/pico-sdk/src/common/boot_picobin_headers/include -isystem /home/tjko/pico/pico-sdk/src/rp2350/boot_stage2/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_fix/rp2040_usb_device_enumeration/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_stdio_uart/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_rand/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_aon_timer/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_powman/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_pwm/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_pio/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_adc/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_i2c/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_spi/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_dma/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_async_context/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_lwip/include -isystem /home/tjko/pico/lwip/src/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_cyw43_arch/include -isystem /home/tjko/pico/pico-sdk/lib/cyw43-driver/src -isystem /home/tjko/pico/pico-sdk/lib/cyw43-driver/firmware -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_cyw43_driver/cybt_shared_bus -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_exception/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_cyw43_driver/include -isystem /home/tjko/pico/pico-sdk/lib/mbedtls/include -isystem /home/tjko/pico/pico-sdk/lib/mbedtls/library -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_mbedtls/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/pico_sha256/include -isystem /home/tjko/pico/pico-sdk/src/rp2_common/hardware_sha256/include -mcpu=cortex-m33 -mthumb -march=armv8-m.main+fp+dsp -mfloat-abi=softfp -mcmse -g -O3 -DNDEBUG -Wall -fmacro-prefix-map=/home/tjko/git/fanpico/= -ffunction-sections -fdata-sections -std=gnu11 -MD -MT CMakeFiles/fanpico.dir/libs/wolfssl/wolfcrypt/src/sp_int.c.o -MF CMakeFiles/fanpico.dir/libs/wolfssl/wolfcrypt/src/sp_int.c.o.d -o CMakeFiles/fanpico.dir/libs/wolfssl/wolfcrypt/src/sp_int.c.o -c /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c
In function 'sp_clear',
    inlined from 'sp_clear' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:5262:6,
    inlined from '_sp_prime_trials' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19298:9,
    inlined from 'sp_prime_is_prime' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19368:15:
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:5272:26: warning: array subscript 'sp_int[0]' is partly outside array bounds of 'sp_int[0]' [-Warray-bounds=]
 5272 |         for (i = 0; i < a->used; i++) {
      |                         ~^~~~~~
In file included from /home/tjko/git/fanpico/libs/wolfssl/wolfssl/wolfcrypt/libwolfssl_sources.h:46,
                 from /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:30:
In function '_sp_prime_trials',
    inlined from 'sp_prime_is_prime' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19368:15:
/home/tjko/git/fanpico/libs/wolfssl/wolfssl/wolfcrypt/types.h:571:61: note: object of size [8, 40] allocated by 'malloc'
  571 |         #define XMALLOC(s, h, t)     ((void)(h), (void)(t), malloc((size_t)(s))) /* native heap */
      |                                                             ^~~~~~~~~~~~~~~~~~~
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:148:28: note: in expansion of macro 'XMALLOC'
  148 |             (n) = (sp_int*)XMALLOC(MP_INT_SIZEOF(s), (h),                      \
      |                            ^~~~~~~
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19278:5: note: in expansion of macro 'ALLOC_SP_INT'
19278 |     ALLOC_SP_INT(n1, a->used + 1, err, NULL);
      |     ^~~~~~~~~~~~
In function 'sp_clear',
    inlined from 'sp_clear' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:5262:6,
    inlined from '_sp_prime_trials' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19299:9,
    inlined from 'sp_prime_is_prime' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19368:15:
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:5272:26: warning: array subscript 'sp_int[0]' is partly outside array bounds of 'unsigned char[40]' [-Warray-bounds=]
 5272 |         for (i = 0; i < a->used; i++) {
      |                         ~^~~~~~
In function '_sp_prime_trials',
    inlined from 'sp_prime_is_prime' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19368:15:
/home/tjko/git/fanpico/libs/wolfssl/wolfssl/wolfcrypt/types.h:571:61: note: object of size [8, 40] allocated by 'malloc'
  571 |         #define XMALLOC(s, h, t)     ((void)(h), (void)(t), malloc((size_t)(s))) /* native heap */
      |                                                             ^~~~~~~~~~~~~~~~~~~
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:148:28: note: in expansion of macro 'XMALLOC'
  148 |             (n) = (sp_int*)XMALLOC(MP_INT_SIZEOF(s), (h),                      \
      |                            ^~~~~~~
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19279:5: note: in expansion of macro 'ALLOC_SP_INT'
19279 |     ALLOC_SP_INT(r, a->used + 1, err, NULL);
      |     ^~~~~~~~~~~~
In function 'sp_clear',
    inlined from 'sp_clear' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:5262:6,
    inlined from '_sp_prime_trials' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19299:9,
    inlined from 'sp_prime_is_prime' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19368:15:
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:5273:22: warning: array subscript 'sp_int[0]' is partly outside array bounds of 'unsigned char[40]' [-Warray-bounds=]
 5273 |             a->dp[i] = 0;
      |             ~~~~~~~~~^~~
In function '_sp_prime_trials',
    inlined from 'sp_prime_is_prime' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19368:15:
/home/tjko/git/fanpico/libs/wolfssl/wolfssl/wolfcrypt/types.h:571:61: note: object of size [8, 40] allocated by 'malloc'
  571 |         #define XMALLOC(s, h, t)     ((void)(h), (void)(t), malloc((size_t)(s))) /* native heap */
      |                                                             ^~~~~~~~~~~~~~~~~~~
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:148:28: note: in expansion of macro 'XMALLOC'
  148 |             (n) = (sp_int*)XMALLOC(MP_INT_SIZEOF(s), (h),                      \
      |                            ^~~~~~~
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19279:5: note: in expansion of macro 'ALLOC_SP_INT'
19279 |     ALLOC_SP_INT(r, a->used + 1, err, NULL);
      |     ^~~~~~~~~~~~
In function 'sp_clear',
    inlined from 'sp_clear' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:5262:6,
    inlined from '_sp_prime_trials' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19298:9,
    inlined from 'sp_prime_is_prime' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19368:15:
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:5273:22: warning: array subscript 'sp_int[0]' is partly outside array bounds of 'sp_int[0]' [-Warray-bounds=]
 5273 |             a->dp[i] = 0;
      |             ~~~~~~~~~^~~
In function '_sp_prime_trials',
    inlined from 'sp_prime_is_prime' at /home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19368:15:
/home/tjko/git/fanpico/libs/wolfssl/wolfssl/wolfcrypt/types.h:571:61: note: object of size [8, 40] allocated by 'malloc'
  571 |         #define XMALLOC(s, h, t)     ((void)(h), (void)(t), malloc((size_t)(s))) /* native heap */
      |                                                             ^~~~~~~~~~~~~~~~~~~
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:148:28: note: in expansion of macro 'XMALLOC'
  148 |             (n) = (sp_int*)XMALLOC(MP_INT_SIZEOF(s), (h),                      \
      |                            ^~~~~~~
/home/tjko/git/fanpico/libs/wolfssl/wolfcrypt/src/sp_int.c:19278:5: note: in expansion of macro 'ALLOC_SP_INT'
19278 |     ALLOC_SP_INT(n1, a->used + 1, err, NULL);
      |     ^~~~~~~~~~~~

```

**Comment by tjko** [comment]
I was using latest GCC (14.3.1) from: https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads

You should see if you compile https://github.com/tjko/fanpico.git

```
mkdir build
cd build
cmake -DPICO_BOARD=pico2_w ..
make -j
```

(more details at: https://github.com/tjko/fanpico?tab=readme-ov-file#building-firmware-images)

**Comment by tjko** [comment]
I tested adding "NO_INLINE" in user_settings.h and that didn't seem to make difference.

**Comment by douzzer** [comment]
@tjko I think we fixed these false positive warnings with #8908, which is merged in our new release (5.8.2).  Can you try again either with the new release, or after cherry picking e1fe18675328ba6bc89c89e4190c47be324bf104?

**Comment by tjko** [comment]
@douzzer, I still see the same warnings, after updating to v5.8.2-stable (decea12e223869c8f8f3ab5a53dc90b69f436eb2)

(happens when compiling for "rp2350-arm-s", but not when compiling for "rp2040")

**Comment by LinuxJedi** [comment]
Hi @tjko,

I've not been able to reproduce this, yet. But I think your GCC version might make a difference here. My OS uses `arm-none-eabi-gcc` version 15.1.0, which also means I'm forced to use the `develop` branch of pico-sdk (raspberrypi/pico-sdk#2448).

When attempting to compile your repo, it fails when compiling mbedtls:

```
[  6%] Building C object CMakeFiles/fanpico.dir/src/filter_lossypeak.c.o
In file included from /home/linuxjedi/tmp/fanpico/src/mbedtls_config.h:75,
from /opt/pico-sdk/src/rp2_common/pico_mbedtls/include/pico_mbedtls_config.h:3,
from /opt/pico-sdk/lib/mbedtls/include/mbedtls/build_info.h:115,
from /opt/pico-sdk/lib/mbedtls/include/mbedtls/error.h:13,
from /home/linuxjedi/tmp/fanpico/src/tls.c:30:
/opt/pico-sdk/lib/mbedtls/include/mbedtls/check_config.h:24:2: warning: #warning "Do not include mbedtls/check_config.h manually! " "This may cause spurious errors. " "It is included automatically at the right point since Mbed TLS 3.0." [-Wcpp]
24 | #warning "Do not include mbedtls/check_config.h manually! " \
|  ^~~~~~~
/opt/pico-sdk/lib/mbedtls/include/mbedtls/check_config.h:226:2: error: #error "MBEDTLS_ENTROPY_C defined, but not all prerequisites"
226 | #error "MBEDTLS_ENTROPY_C defined, but not all prerequisites"
|  ^~~~~
/opt/pico-sdk/lib/mbedtls/include/mbedtls/check_config.h:261:2: error: #error "MBEDTLS_GCM_C defined, but not all prerequisites"
261 | #error "MBEDTLS_GCM_C defined, but not all prerequisites"
|  ^~~~~
/opt/pico-sdk/lib/mbedtls/include/mbedtls/check_config.h:354:2: error: #error "MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED defined, but not all prerequisites"
354 | #error "MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED defined, but not all prerequisites"
|  ^~~~~
/opt/pico-sdk/lib/mbedtls/include/mbedtls/check_config.h:410:2: error: #error "MBEDTLS_MD_C defined, but no hash algorithm"
410 | #error "MBEDTLS_MD_C defined, but no hash algorithm"
|  ^~~~~
/opt/pico-sdk/lib/mbedtls/include/mbedtls/check_config.h:893:2: error: #error "MBEDTLS_SSL_TLS_C defined, but not all prerequisites"
893 | #error "MBEDTLS_SSL_TLS_C defined, but not all prerequisites"
|  ^~~~~
make[2]: *** [CMakeFiles/fanpico.dir/build.make:205: CMakeFiles/fanpico.dir/src/tls.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  6%] Building C object CMakeFiles/fanpico.dir/src/filter_sma.c.o
make[1]: *** [CMakeFiles/Makefile2:2559: CMakeFiles/fanpico.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

We will try to do a containerised build with ARM's own GCC version soon.

**Comment by tjko** [comment]
@LinuxJedi,  compiling should now be fixed against the "develop" branch of pico-sdk.

**Comment by LinuxJedi** [comment]
> [@LinuxJedi](https://github.com/LinuxJedi), compiling should now be fixed against the "develop" branch of pico-sdk.

Thanks! Yes, this compiles fine with GCC 15.1.0. I'll see what I can do about testing with ARM's own fork.

**Comment by LinuxJedi** [comment]
@tjko to try and get on the same page, I have created this Dockerfile which should compile our example using ARM's version of GCC and wolfSSL 5.8.2 with latest master branch of Pico SDK. I could not get it to fail.

Can you please modify this to reproduce the failure you are seeing? It should make it easier to reproduce the problem.

You should be able to build with:
```
docker build -t wolfssl-pico .
```

[Dockerfile.txt](https://github.com/user-attachments/files/21413328/Dockerfile.txt)

**Comment by tjko** [comment]
@LinuxJedi , attached is Dockerfile that produces the compiler warnings

```
...
[ 76%] Building C object CMakeFiles/fanpico.dir/workspace/wolfssl/wolfcrypt/src/sp_int.c.o
In function 'sp_clear',
    inlined from 'sp_clear' at /workspace/wolfssl/wolfcrypt/src/sp_int.c:5262:6,
    inlined from '_sp_prime_trials' at /workspace/wolfssl/wolfcrypt/src/sp_int.c:19298:9,
    inlined from 'sp_prime_is_prime' at /workspace/wolfssl/wolfcrypt/src/sp_int.c:19368:15:
/workspace/wolfssl/wolfcrypt/src/sp_int.c:5272:26: warning: array subscript 'sp_int[0]' is partly outside array bounds of 'sp_int[0]' [-Warray-bounds=]
 5272 |         for (i = 0; i < a->used; i++) {
      |                         ~^~~~~~
In file included from /workspace/wolfssl/wolfssl/wolfcrypt/libwolfssl_sources.h:46,
                 from /workspace/wolfssl/wolfcrypt/src/sp_int.c:30:
In function '_sp_prime_trials',
    inlined from 'sp_prime_is_prime' at /workspace/wolfssl/wolfcrypt/src/sp_int.c:19368:15:
/workspace/wolfssl/wolfssl/wolfcrypt/types.h:571:61: note: object of size [8, 40] allocated by 'malloc'
  571 |         #define XMALLOC(s, h, t)     ((void)(h), (void)(t), malloc((size_t)(s))) /* native heap */
      |                                                             ^~~~~~~~~~~~~~~~~~~
/workspace/wolfssl/wolfcrypt/src/sp_int.c:148:28: note: in expansion of macro 'XMALLOC'
  148 |             (n) = (sp_int*)XMALLOC(MP_INT_SIZEOF(s), (h),                      \
      |                            ^~~~~~~
/workspace/wolfssl/wolfcrypt/src/sp_int.c:19278:5: note: in expansion of macro 'ALLOC_SP_INT'
19278 |     ALLOC_SP_INT(n1, a->used + 1, err, NULL);
      |     ^~~~~~~~~~~~
...
```

[Dockerfile.fanpico.txt](https://github.com/user-attachments/files/21425148/Dockerfile.fanpico.txt)

**Comment by LinuxJedi** [comment]
@tjko I have discussed this with @douzzer internally and it is a GCC bug with the array bounds check. Whilst it is getting better, GCC has had many bugs with this warning.

I recommend either upgrading your GCC to 15.x (which fixed a bunch, including this) or disabling the warning with `-Wno-array-bounds`.

I'll close the ticket at this time, but please feel free to reopen if you have any further questions regarding this. Thank you for reporting it and for using wolfSSL.
